jerrod bates
restincode/restincode pull request #259
Opened 2023-12-08 18:42 UTC by peterclemenko

closes #253

2023-12-09 21:07 UTC, mauvehed requested changes
Thank you for your contribution! This greatly helps the project with our incredible backlog.

Please note the few corrections I requested inline and also please make a new entry for Jerrod in the `/peoplelist.json` file. The _filename_ parameter should simply be the same name as the jerrodbates.json file name, minus the extension.

Thank you!

2023-12-09 21:07 UTC, mauvehed commented on people/jerrodbates.json
> +  "lastname": "Bates",
Please re-insert the handle field but leave it empty, without this it will produce an "undefined" message on the website

2023-12-09 21:07 UTC, mauvehed commented on people/jerrodbates.json
> +  "contributions": [
Please add a siteurl value or remove the contributions section.

2023-12-10 23:01 UTC, peterclemenko commented
updated, try now

2023-12-10 23:32 UTC, mauvehed commented
> updated, try now

Awesome, just add him to `peoplelist.json` in the root folder and we're all set.

2023-12-11 09:16 UTC, peterclemenko commented
Done

2023-12-11 16:16 UTC, mauvehed approved these changes

2023-12-11 16:18 UTC, mauvehed commented
Thank you so very much, @peterclemenko. It means a lot to us to have community members participate in the actual creation of content for this project. Every single page or person helps. And thank you for taking the feedback and still making the changes and seeing this PR through!

2023-12-11 16:18 UTC, merged